/* Demo V6.3.1 — explicações leigas, score contextualizado e histórico legível. */
(() => {
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'N/D';
  const pct=v=>Number.isFinite(Number(v))?`${Number(v)>0?'+':''}${n(v,1)}%`:'N/D';
  const pp=v=>Number.isFinite(Number(v))?`${Number(v)>0?'+':''}${n(v,2)} p.p.`:'N/D';
  const dmy=v=>{if(!v)return'N/D';const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('pt-BR');};
  let BT={};
  function score(i){const x=Number(i?.conviccao?.pontos);if(Number.isFinite(x))return x;const s=String(i?.conviccao??''),m=s.match(/score\s*(-?\d+(?:\.\d+)?)/i);return m?Number(m[1]):null;}
  function level(i){const x=score(i);return !Number.isFinite(x)?'N/D':x>=4?'ALTA':x>=2?'MÉDIA':'BAIXA';}
  function stars(i){const x=score(i);return !Number.isFinite(x)?'':x>=4?'★★★':x>=2?'★★':'★';}
  function strategy(i){if(['COMPRA_FORTE','ACUMULACAO'].includes(i?.categoria))return'Comprar uma correção dentro de uma tendência de alta';if(i?.categoria==='REVERSAO_INICIAL')return'Tentar capturar o início de uma recuperação';if(['REALIZACAO_PARCIAL','SAIDA_CONFIRMADA','TENDENCIA_ESTICADA'].includes(i?.categoria))return'Proteger lucro e administrar risco';return'Observar até surgir um sinal mais claro';}
  function decision(i){const x=score(i),low=Number.isFinite(x)&&x<2,high=Number.isFinite(x)&&x>=4;switch(i?.categoria){case'ACUMULACAO':return low?['Possível entrada, mas confirmação fraca','A zona de acumulação apareceu, porém as confirmações adicionais ainda são insuficientes. Melhor observar ou testar posição pequena.']:high?['Entrada gradual com boa confirmação','A correção ocorreu dentro de tendência preservada e várias confirmações ajudam a tese.']:['Entrada gradual com confirmação moderada','O timing existe, mas ainda há fatores que limitam a confiança.'];case'COMPRA_FORTE':return low?['Gatilho técnico forte, confirmação geral fraca','O timing de compra apareceu, mas os demais fatores ainda não confirmam com força.']:high?['Gatilho técnico com boa confirmação','Timing e confirmações adicionais estão alinhados.']:['Gatilho técnico com confirmação moderada','Há sinal de entrada, mas não é o cenário de maior convicção.'];case'REVERSAO_INICIAL':return low?['Tentativa de recuperação ainda fraca','A queda perdeu força, mas a retomada ainda não está bem confirmada.']:high?['Recuperação com boa confirmação','A reversão em formação tem várias confirmações adicionais.']:['Recuperação em formação','A queda perdeu força e há confirmação moderada.'];case'APROXIMACAO':return['Aguardar','Está perto de um gatilho, mas ele ainda não aconteceu.'];case'TENDENCIA_ESTICADA':return['Alta forte, mas comprar agora ficou menos atraente','O ativo já avançou bastante; quem já tem deve pensar em proteção, não em perseguir preço.'];case'REALIZACAO_PARCIAL':return['Alta perdendo força','A força diminuiu; vale revisar proteção ou redução parcial.'];case'SAIDA_CONFIRMADA':return['Sinal de saída','A deterioração ficou mais consistente.'];default:return['Sem decisão forte','Ainda não há um sinal operacional claro.'];}}
  function trigger(i){const out=[];if(i?.categoria==='ACUMULACAO'){out.push(`IFR ${n(i.ifr,1)}: força recente enfraquecida, dentro da faixa usada para procurar acumulação.`);out.push(i?.regime?.code==='ALTA_TOTAL'||/Alta Total/i.test(String(i?.regime?.label??i?.regime))?'Tendência de curto e longo prazo segue de alta.':'A tendência não está totalmente confirmada.');if(Number.isFinite(i.mm20)&&Number.isFinite(i.preco))out.push(`Preço ${i.preco<=i.mm20?'está na/abaixo da':'está acima da'} média de 20 dias.`);}else if(i?.categoria==='COMPRA_FORTE'){out.push(`IFR ${n(i.ifr,1)}: correção forte.`);out.push('Preço chegou à zona técnica de entrada do modelo.');}else if(i?.categoria==='REVERSAO_INICIAL'){out.push('A força da queda diminuiu e o IFR começou a reagir.');}return out;}
  function hint(label,i){const l=label.toLowerCase();if(l.includes('ifr diário')){const x=Number(i.ifr);if(x<=45)return'IFR mede força de 0 a 100. Abaixo de 45 = preço enfraquecido; pode virar oportunidade somente se o restante da estrutura ajudar.';if(x>=70)return'Acima de 70 = movimento muito forte, mas possivelmente esticado para nova compra.';return'Perto de 50 = força intermediária/neutra.';}if(l.includes('ifr semanal'))return'Versão mais lenta do IFR. Serve para confirmar se a direção diária também aparece numa janela maior; perto de 50 = neutro.';if(l.includes('volume relativo')){const x=Number(i.volRatio);return Number.isFinite(x)?`${n(x,2)}x significa cerca de ${n(x*100,0)}% do volume normal. Abaixo de 1x confirma menos; acima de 1x confirma melhor.`:'';}if(l.includes('drawdown')){const x=Number(i.drawdown52);return Number.isFinite(x)?`Está ${Math.abs(x).toFixed(1)}% abaixo da máxima de 1 ano. Pode representar desconto, mas só é bom se a empresa e a tendência continuarem saudáveis.`:'';}if(l==='dy'){const x=Number(i.dy??i.dyVal);return Number.isFinite(x)?`Dividend Yield: renda anual de dividendos em relação ao preço. ${n(x,1)}% equivale a cerca de ${n(x,1)} para cada 100 investidos na referência atual, se o pagamento se repetir. O scanner considera ≥ 4% como reforço.`:'';}if(l.includes('teto de entrada')){const teto=Number(i?.valuation?.tetoEntrada),p=Number(i.preco);return Number.isFinite(teto)&&Number.isFinite(p)&&p/teto>2?'Referência muito distante do preço atual: trate com baixa confiança, pois o método de valuation pode não ser adequado para este tipo de empresa.':'Preço de referência com margem de segurança; não é uma ordem automática de compra.';}return'';}
  function patchMetrics(i){q('#detail')?.querySelectorAll('.metric').forEach(m=>{const s=m.querySelector('span');if(!s)return;const h=hint(s.textContent.trim(),i);if(!h)return;let sm=m.querySelector('.v631hint');if(!sm){sm=document.createElement('small');sm.className='v631hint';sm.style.cssText='display:block;margin-top:4px;color:#64748b;line-height:1.35';m.appendChild(sm);}sm.textContent=h;});}
  function patchStatus(i){qa('#radar tr[data-k]').forEach(tr=>{const it=S.items.find(x=>`${x.market}:${x.ticker}`===tr.dataset.k);if(!it||!tr.children[1])return;const text=tr.children[1].textContent.replace(/[★☆]+/g,'').trim();if(['COMPRA_FORTE','ACUMULACAO','REVERSAO_INICIAL'].includes(it.categoria))tr.children[1].textContent=`${text} ${stars(it)}`.trim();});const tag=q('#detail .tag');if(tag&&['COMPRA_FORTE','ACUMULACAO','REVERSAO_INICIAL'].includes(i?.categoria)){tag.textContent=tag.textContent.replace(/[★☆]+/g,'').trim()+' '+stars(i);}}
  function patchSimple(i){const sec=q('#demoSimple');if(!sec)return;const box=sec.querySelector('.box');if(!box)return;const d=decision(i),x=score(i),why=trigger(i);box.innerHTML=`<b>${esc(d[0])}</b><br>${esc(d[1])}<br><div style="margin-top:6px"><b>Estratégia:</b> ${esc(strategy(i))}</div>${why.length?`<div style="margin-top:6px"><b>Por que este gatilho apareceu:</b><ul style="margin:4px 0 0;padding-left:18px">${why.map(z=>`<li>${esc(z)}</li>`).join('')}</ul></div>`:''}<div style="margin-top:6px"><b>Convicção:</b> ${level(i)}${Number.isFinite(x)?` · score líquido ${n(x,1)}`:''}. <span class="muted">Baixa &lt; 2 · média 2 a &lt; 4 · alta ≥ 4. Não é “1 de 10”; o que importa é a faixa atingida.</span></div>`;}
  function horizon(label,d){if(!d)return'';const c=d.positiveCount??(Number.isFinite(d.positiveRate)&&Number.isFinite(d.n)?Math.round(d.positiveRate*d.n/100):null);return `<tr><td>${label}</td><td>${c==null?'N/D':`${c} de ${d.n}`}</td><td>${d.positiveRate==null?'N/D':n(d.positiveRate,1)+'%'}</td><td>${pct(d.medianReturn)}</td><td>${pp(d.medianAlpha)}</td></tr>`;}
  function patchBacktest(i){const old=q('#demoBacktest');if(!old)return;const j=BT[`${i.market}:${i.ticker}`];old.innerHTML='<h4>O que aconteceu quando um cenário parecido apareceu no passado?</h4>';const box=document.createElement('div');box.className='box';if(!j||j.error){box.innerHTML=`<span class="muted">${j?.error?'Histórico indisponível para este ativo.':'Carregando histórico...'}</span>`;old.appendChild(box);return;}const d20=j.d20??{},risk=j.risk20??{},alpha=Number(d20.medianAlpha),alphaText=Number.isFinite(alpha)?(alpha>0?`superou ${j.benchmark||'o índice'} em ${pp(alpha)}`:alpha<0?`ficou atrás de ${j.benchmark||'o índice'} em ${pp(Math.abs(alpha))}`:'empatou com o índice'):'sem comparação com índice';box.innerHTML=`<b>Período analisado: ${dmy(j.periodStart)} a ${dmy(j.periodEnd)}</b><br>Nos últimos 5 anos, um cenário técnico parecido apareceu <b>${j.n??0} vez(es)</b>.${j.n<20?' <span class="warn">Amostra pequena.</span>':''}<table style="width:100%;margin-top:7px;font-size:10px"><thead><tr><th>Depois de</th><th>Subiu</th><th>% positivo</th><th>Resultado típico</th><th>Vs. índice</th></tr></thead><tbody>${horizon('1 semana',j.d5)}${horizon('1 mês',j.d20)}${horizon('3 meses',j.d60)}</tbody></table><div class="kv" style="margin-top:7px"><div class="metric"><span>Melhor ponto típico em 1 mês</span><b>${pct(risk.mfeMedian)}</b><small>Maior ganho alcançado no caminho.</small></div><div class="metric"><span>Pior ponto típico em 1 mês</span><b>${pct(risk.maeMedian)}</b><small>Pior nível alcançado no caminho; se positivo, o preço nem chegou a ficar abaixo do ponto inicial.</small></div></div><div class="note" style="margin-top:6px"><b>Em português:</b> após cerca de 1 mês, ${d20.positiveCount??'N/D'} de ${d20.n??0} casos terminaram acima; o resultado típico foi ${pct(d20.medianReturn)} e ${alphaText}. Na demo buscamos um <b>perfil parecido</b>; no painel privado o gatilho do motor é reexecutado exatamente.</div>`;old.appendChild(box);}
  function patch(i){if(!i)return;setTimeout(()=>{patchStatus(i);patchSimple(i);patchMetrics(i);patchBacktest(i);},0);}
  const prev=window.select;if(typeof prev==='function')window.select=function(i){const r=prev(i);S.selected=i;patch(i);return r;};
  fetch('./backtest-data.json',{cache:'no-store'}).then(r=>r.json()).then(j=>{BT=j.items||{};if(S?.selected)patch(S.selected);}).catch(()=>{});
  setTimeout(()=>{if(S?.items?.length){patchStatus(S.selected||S.items[0]);if(S.selected)patch(S.selected);}},1000);
})();
