/* Demo V6.3 — linguagem simples, favoritos locais e validação histórica técnica. */
(() => {
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc3=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=(v,d=1)=>Number.isFinite(v)?Number(v).toFixed(d):'N/D';
  const pct=v=>Number.isFinite(v)?`${v>0?'+':''}${n(v,1)}%`:'N/D';
  const pp=v=>Number.isFinite(v)?`${v>0?'+':''}${n(v,2)} pp`:'N/D';
  const KEY='scannerQuantDemoFavoritesV63';let favMode=false,BT={};
  const getFav=()=>{try{return new Set(JSON.parse(localStorage.getItem(KEY)||'[]'));}catch{return new Set();}};
  const saveFav=s=>localStorage.setItem(KEY,JSON.stringify([...s]));
  const k=i=>`${i.market}:${i.ticker}`;
  const SIMPLE={COMPRA_FORTE:['Compra forte','Vários sinais favoráveis coincidiram. É o gatilho de entrada mais forte do modelo, mas ainda exige controle de risco.'],ACUMULACAO:['Comprar aos poucos','A estrutura principal segue favorável, mas o ativo está em correção. A lógica é entrada gradual.'],REVERSAO_INICIAL:['Queda perdendo força','A baixa começou a perder força e o ativo tenta voltar a subir; a reversão ainda está em formação.'],RECUPERACAO:['Recuperação em andamento','O curto prazo melhorou, mas a tendência longa ainda não confirmou completamente.'],APROXIMACAO:['Aguardar confirmação','Está perto de um gatilho, mas ainda faltam condições para entrada.'],TENDENCIA_ESTICADA:['Alta forte, mas preço avançado','A tendência segue positiva, porém o ponto para nova compra está pior. Quem já tem pode proteger lucro.'],REALIZACAO_PARCIAL:['Alta perdendo força','Há deterioração inicial; para quem já está posicionado, pode fazer sentido proteger ou reduzir parte.'],SAIDA_CONFIRMADA:['Sinal de saída','A deterioração ficou mais consistente; o modelo recomenda reavaliar a posição.'],NEUTRO:['Sem sinal claro','O conjunto ainda não aponta oportunidade ou risco forte.']};
  const simple=i=>SIMPLE[i?.categoria]||['Leitura em observação','Leia o sinal junto com tendência, força do movimento, volume e valuation.'];
  function plainRegime(i){const r=String(i?.regime?.label??i?.regime??'');if(/Alta Total/i.test(r))return'Tendência de alta no curto e no longo prazo.';if(/Baixa Curto \/ Alta Longo/i.test(r))return'O longo prazo ainda é de alta, mas o curto prazo está corrigindo.';if(/Alta Curto \/ Baixa Longo/i.test(r))return'O curto prazo reagiu, mas o longo prazo ainda não confirmou alta.';if(/Baixa Total/i.test(r))return'Tendência de baixa no curto e no longo prazo.';return'Estrutura ainda sem leitura simples disponível.';}
  function ensureFavButton(){if(q('#favFilter'))return;const tb=q('#toolbar');if(!tb)return;const b=document.createElement('button');b.id='favFilter';b.textContent='★ Meus favoritos';b.onclick=()=>{favMode=!favMode;b.classList.toggle('active',favMode);if(favMode)qa('#toolbar button').filter(x=>x!==b).forEach(x=>x.classList.remove('active'));renderRadar();patchRows();};tb.appendChild(b);}
  function patchRows(){const fav=getFav();qa('#radar tr[data-k]').forEach(tr=>{if(favMode&& !fav.has(tr.dataset.k)){tr.style.display='none';return;}tr.style.display='';const cell=tr.children[0];if(!cell||cell.querySelector('.favStar'))return;const i=S.items.find(x=>k(x)===tr.dataset.k),b=document.createElement('button');b.className='favStar';b.style.cssText='border:0;background:transparent;cursor:pointer;font-size:14px;margin-right:4px;padding:0';b.textContent=fav.has(tr.dataset.k)?'★':'☆';b.title='Favoritar neste navegador';b.onclick=e=>{e.stopPropagation();const s=getFav();s.has(tr.dataset.k)?s.delete(tr.dataset.k):s.add(tr.dataset.k);saveFav(s);patchRows();if(S.selected&&k(S.selected)===tr.dataset.k)patchDetail(S.selected);};cell.prepend(b);});}
  function backtestHtml(i){const j=BT[k(i)];if(!j)return'<span class="muted">Ainda não pré-calculado para este ativo nesta demo.</span>';if(j.error)return`<span class="muted">Histórico indisponível: ${esc3(j.error)}</span>`;const d=j.d20||{},r=j.risk20||{};return`<div class="kv"><div class="metric"><span>Ocorrências semelhantes</span><b>${j.n??0}</b></div><div class="metric"><span>D+20 positivo</span><b>${d.positiveRate==null?'N/D':n(d.positiveRate,1)+'%'}</b></div><div class="metric"><span>Retorno mediano D+20</span><b>${pct(d.medianReturn)}</b></div><div class="metric"><span>Alpha mediano D+20</span><b>${pp(d.medianAlpha)}</b><small>${j.benchmark?`vs ${esc3(j.benchmark)}`:'benchmark N/D'}</small></div><div class="metric"><span>MFE mediana 20d</span><b>${pct(r.mfeMedian)}</b></div><div class="metric"><span>MAE mediana 20d</span><b>${pct(r.maeMedian)}</b></div></div><div class="note" style="margin-top:6px">${esc3(j.method||'Perfil técnico semelhante.')} ${j.n<20?'Amostra pequena: interpretar com cautela.':''}</div>`;}
  function patchDetail(i){const d=q('#detail');if(!d||!i)return;q('#demoSimple')?.remove();q('#demoBacktest')?.remove();const s=simple(i),fav=getFav(),a=document.createElement('div');a.id='demoSimple';a.className='section';a.innerHTML=`<h4>Em linguagem simples</h4><div class="box"><b>${esc3(s[0])}</b><br>${esc3(s[1])}<br><span class="muted">${esc3(plainRegime(i))}</span><br><button class="chip" id="demoFav" style="margin-top:7px">${fav.has(k(i))?'★ Favorito':'☆ Favoritar'}</button></div>`;a.querySelector('#demoFav').onclick=()=>{const f=getFav();f.has(k(i))?f.delete(k(i)):f.add(k(i));saveFav(f);patchDetail(i);patchRows();};const tech=[...d.querySelectorAll('.section h4')].find(h=>/Leitura técnica/i.test(h.textContent))?.closest('.section');tech?tech.before(a):d.prepend(a);const b=document.createElement('div');b.id='demoBacktest';b.className='section';b.innerHTML=`<h4>Validação histórica técnica</h4><div class="box"><b>Como perfis técnicos semelhantes se comportaram nos últimos 5 anos</b><br><span class="muted">Sem usar fundamentos ou valuation futuros; isto é validação estatística, não garantia de resultado.</span><div style="margin-top:7px">${backtestHtml(i)}</div></div>`;d.appendChild(b);}
  const oldRender=window.renderRadar;if(typeof oldRender==='function')window.renderRadar=function(){const r=oldRender.apply(this,arguments);patchRows();return r;};
  const oldSelect=window.select;if(typeof oldSelect==='function')window.select=function(i){const r=oldSelect(i);S.selected=i;patchDetail(i);patchRows();return r;};
  async function loadBt(){try{BT=(await fetch('./backtest-data.json',{cache:'no-store'}).then(r=>r.json())).items||{};}catch{BT={};}if(S.selected)patchDetail(S.selected);}
  ensureFavButton();setTimeout(()=>{ensureFavButton();patchRows();loadBt();if(S.items?.length&&!S.selected){S.selected=S.items[0];patchDetail(S.selected);}},700);
})();
