/* Demo V6.3.2 — significado primeiro + personalização local do radar. */
(() => {
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const KEY='scannerQuantDemoHiddenRadarV632';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const key=i=>`${i.market}:${i.ticker}`;
  const hidden=()=>{try{return new Set(JSON.parse(localStorage.getItem(KEY)||'[]'));}catch{return new Set();}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify([...s]));
  function score(i){const c=i?.conviccao;if(c&&typeof c==='object'&&Number.isFinite(c.pontos))return c.pontos;const m=String(c??'').match(/score\s*(-?\d+(?:\.\d+)?)/i);return m?Number(m[1]):null;}
  function lvl(i){const s=score(i);return !Number.isFinite(s)?'sem nota':s>=4?'confirmação alta':s>=2?'confirmação média':'confirmação baixa';}
  function sit(i){switch(i?.categoria){case'COMPRA_FORTE':return['🚨','GATILHO DE ENTRADA',`preço chegou à zona de compra · ${lvl(i)}`];case'ACUMULACAO':return['🟡','POSSÍVEL ENTRADA',`correção dentro de tendência de alta · ${lvl(i)}`];case'REVERSAO_INICIAL':return['🟢','QUEDA PERDENDO FORÇA',`tentativa de recuperação · ${lvl(i)}`];case'RECUPERACAO':return['🌱','RECUPERAÇÃO EM ANDAMENTO','preço reagindo; confirmação ainda em construção'];case'APROXIMACAO':return['⚠️','AGUARDAR','perto de um gatilho, mas ainda não confirmado'];case'TENDENCIA_ESTICADA':return['🟣','ALTA FORTE; NÃO PERSEGUIR PREÇO','bom para quem já tem; pior ponto para nova compra'];case'REALIZACAO_PARCIAL':return['🟠','ALTA PERDENDO FORÇA','revisar proteção ou reduzir parte'];case'SAIDA_CONFIRMADA':return['🔴','SAÍDA / REDUZIR RISCO','deterioração mais consistente'];case'BLOQUEADO':case'BLOQUEADO_WATCH':return['🛑','NÃO ENTRAR AGORA','preço pode parecer barato, mas estrutura ainda é fraca'];default:return['⚪','SEM SINAL CLARO','nenhuma decisão forte no momento'];}}
  function patchRows(){const h=hidden();qa('#radar tr[data-k]').forEach(tr=>{const i=S.items.find(x=>key(x)===tr.dataset.k);if(!i)return;tr.style.display=h.has(tr.dataset.k)?'none':'';if(tr.children[1]){const s=sit(i);tr.children[1].innerHTML=`<div style="font-weight:700">${s[0]} ${esc(s[1])}</div><small style="display:block;color:#64748b;margin-top:2px">${esc(s[2])}</small>`;tr.children[1].title=`Termo técnico: ${i.categoria}. O texto mostra o significado prático primeiro.`;}});}
  function ensureButton(){if(q('#demoRadarManage'))return;const tb=q('#toolbar');if(!tb)return;const b=document.createElement('button');b.id='demoRadarManage';b.textContent='⚙️ Meu radar';b.onclick=openManager;tb.appendChild(b);}
  function openManager(){let p=q('#demoRadarPanel');if(p){p.hidden=!p.hidden;return;}const radar=q('#radar');if(!radar)return;p=document.createElement('div');p.id='demoRadarPanel';p.className='section';p.style.marginBottom='10px';p.innerHTML=`<div class="box"><b>Personalizar meu radar</b><br><span class="muted">Nesta demo, você pode adicionar ou remover ativos do catálogo público no seu próprio navegador. INTC, TSM, MCD e TSLA foram incluídos no catálogo.</span><div style="display:flex;gap:6px;margin-top:9px"><input id="demoRadarTicker" placeholder="INTC, TSM, MCD, TSLA..." style="flex:1"><button class="chip" id="demoRadarAdd">Adicionar</button><button class="chip" id="demoRadarClose">Fechar</button></div><div id="demoRadarMsg" class="muted" style="margin-top:6px"></div><div id="demoRadarList" style="display:flex;flex-wrap:wrap;gap:5px;margin-top:9px;max-height:140px;overflow:auto"></div></div>`;radar.parentElement.insertBefore(p,radar);renderManager();q('#demoRadarAdd').onclick=()=>{const t=q('#demoRadarTicker').value.trim().toUpperCase(),i=S.items.find(x=>x.ticker===t);const msg=q('#demoRadarMsg');if(!i){msg.textContent='Esse ticker não está no catálogo publicado desta demo. No painel privado, qualquer ticker pode ser incluído no próximo scan.';return;}const h=hidden();h.delete(key(i));save(h);q('#demoRadarTicker').value='';msg.textContent=`${t} adicionado ao seu radar.`;renderRadar();patchRows();renderManager();};q('#demoRadarClose').onclick=()=>p.hidden=true;}
  function renderManager(){const box=q('#demoRadarList');if(!box)return;const h=hidden();box.innerHTML=S.items.slice().sort((a,b)=>a.market.localeCompare(b.market)||a.ticker.localeCompare(b.ticker)).map(i=>`<button class="chip demoToggleRadar" data-k="${esc(key(i))}" title="${h.has(key(i))?'Adicionar':'Remover'} do meu radar">${h.has(key(i))?'＋':'×'} ${esc(i.ticker)}</button>`).join('');box.querySelectorAll('.demoToggleRadar').forEach(b=>b.onclick=()=>{const h2=hidden();h2.has(b.dataset.k)?h2.delete(b.dataset.k):h2.add(b.dataset.k);save(h2);renderRadar();patchRows();renderManager();});}
  const oldRender=window.renderRadar;if(typeof oldRender==='function')window.renderRadar=function(){const r=oldRender.apply(this,arguments);setTimeout(patchRows,0);return r;};
  setTimeout(()=>{ensureButton();patchRows();},1200);
})();
